name: kanbansim
description: University project of desktop Flutter application which allows to simulate developer team's work in accordance with Kanban method. 

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  pluto_menu_bar: ^0.1.4
  google_fonts: ^2.0.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

