name: kanbansim
description: University project of desktop Flutter application which allows to simulate developer team's work in accordance with Kanban method. 

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  overlay_support: ^1.2.0
  vs_scrollbar: ^0.2.0
  pluto_menu_bar: ^1.0.0-nullsafety.0
  filesystem_picker: ^1.0.4
  google_fonts: ^2.0.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02
  file_picker_cross: ^4.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  expandable: ^5.0.1
  universal_html: ^2.0.8
  bitsdojo_window: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_intl:
  main_locale: en_US
  enabled: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/